### ISSUE TITLE
Fix Error when open modifications window

### ISSUE THREAD

**Issue by Chenger1** [Chenger1/stellaris-trpack#58]
ModsListWindow
`Traceback (most recent call last):
  File "MainInterface.py", line 118, in show_mods_list_window
    mod_list_window = ModsListWindow(self)
  File "stellaris-trpack\GUI\GUI_windows\ModsListWindow.py", line 52, in __init__
    self.paint_elements()
  File "stellaris-trpack\GUI\GUI_windows\ModsListWindow.py", line 195, in paint_elements
    value = self.get_total_value(elem.modId.split('_')[-1].split('.')[0])
AttributeError: 'NoneType' object has no attribute 'split'
'`

**Comment by Chenger1** [comment]
Done
